### ISSUE TITLE
Page options outside index.js

### ISSUE THREAD

**Issue by nekloth** [simonhaenisch/md-to-pdf#1]
It can be usefull to have the pages options (page size, margins) in parameters in command line.

**Comment by simonhaenisch** [comment]
Would you prefer passing them in as a JSON string? e. g.

```
--page-options "{ format: 'A4', border: { top: '30mm', right: '40mm', bottom: '30mm', left: '20mm' } }"
```

... or each one individually as flags? e. g.

```
--page-format A4 --border-top 30mm --border-right 40mm [...]
```

Could also do a CSS-like border option, e. g.

* `--border 30mm` => all borders
* `--border "30mm 40mm"` => top/bottom, left/right
* `--border "30mm 40mm 50mm"` => top, left/right, bottom
* `--border "30mm 40mm 50mm 60mm"` => top, right, bottom, left

**Comment by nekloth** [comment]
May I suggest the JSON string? 

It seems more flexible if you want to add further options later on.

CSS file could be also part of these options.

**Comment by nekloth** [comment]
And having these options in the document itself, like the header/footer ?

This may be at the opposite of the spirit of split content from format... 

Separated file, beside the md ? Then the CLI should accept something like:
```--page-options-file /home/user/nekloth/options.json```

What do you think about it?

**Comment by simonhaenisch** [comment]
Yeah was thinking of doing that as well. I guess a yaml front-matter inside the markdown file would be nice as well. The markdown parser I'm using (marked) doesn't support front matter but I can probably find a package to do it.

BTW I just saw that marked supports syntax highlighting, would that be something you are interested in? (I only used it for non-coding assignments so far)

**Comment by nekloth** [comment]
I definitely prefer the formatting options *outside* the MD file, in an external file (like the CSS is):
*   to keep the original idea of split content (md), format (css) and then pages options
*   to allow ONE option file for several md --> if you need a change, this will be applied to all, avoiding copy/paste inside md files
*   to keep the possibility to easy generate several version of the same PDF doc but in different formats.

I saw that some book editors (paper version) accepted *asciidoc* (similar to md) as author's input file. Once they have this file, they apply the page options they want, according to printing constraints.So, let's keep that logic, don't you think ?

This can be a yaml/json, does not matter for me. Yaml is maybe a little bit more human readable.

Regarding highlights, that is not part of my today's need, but ... who knows ! :)

Thanks

**Comment by simonhaenisch** [comment]
I already started working on this, but I'm going to be away for 8 days, so I won't be able to finish it. Will try to get it done as soon as possible when I'm back.

**Comment by nekloth** [comment]
Thank you for the update. I'm not in a rush, I can wait ! ;-)

**Comment by simonhaenisch** [comment]
Hi sorry it took so freaking long, just wanted to let you know that I finally got to work on this. Will update the readme later today and publish the whole thing as an npm package. A few things still need to be added but at least there are some basic cli args available now.

**Comment by simonhaenisch** [comment]
Also added an option `--config-file` that accepts the path to a `.json` file (or a `.js` file that exports an object). See the readme for an example file.
