### ISSUE TITLE
bug: Background color with dark code theme isn't dark

### ISSUE THREAD

**Issue by mauricedb** [simonhaenisch/md-to-pdf#103]
**Context:**

- version (`md-to-pdf -v`): 5.0.0
- platform (Unix, macOS, Windows): Windows
- node version: v14.18.0

**Describe the bug:**

I am trying to convert a Markdown document with TypeScript code using the GitHub Dark highlight style using the command `md-to-pdf .\doc.md --highlight-style=github-dark`. However the background for all code remains light. The code text colors are updated making the text almost unreadable.

![image](https://user-images.githubusercontent.com/3197730/142042272-eb381902-f0e0-4866-a767-4a7930c2d99b.png)

When rendering to HTML I noticed the line `background-color: #f8f8f8 !important;` [here](https://github.com/simonhaenisch/md-to-pdf/blob/491ab6beeed2fe1517ecb8a76ec5d74afc83d1ce/markdown.css#L84) that seems to overrule the background color from `github-dark.css`.

### With !important
![image](https://user-images.githubusercontent.com/3197730/142043355-f77dd3ec-a8b8-4e57-ae9c-51f5226f7c16.png)

### Without !important
![image](https://user-images.githubusercontent.com/3197730/142043312-cab693a6-ec4c-4adb-ae76-b6d118016e89.png)

**Comment by simonhaenisch** [comment]
Hey thanks for the bug report, i'll get this fixed today.

**Comment by mauricedb** [comment]
Thanks for the fast fix.
