### ISSUE TITLE
Control image size in output PDF?

### ISSUE THREAD

**Issue by luckman212** [simonhaenisch/md-to-pdf#111]
**Context:**

- version: 5.0.1
- platform: macOS
- node version: v17.3.1

I have a markdown file like this
```md
# Foo

Blah blah

![img|200](images/something.png)
```
In the above scenario, **something.png** is 1000x1000px (example). I am trying to control its size to 200px wide.

When I output this using `md-to-pdf`, the image is full size. Is there any workaround or other syntax I can use?
Thank you 🙏

**Comment by simonhaenisch** [comment]
Yeah, of course...

```markdown
---
css: img { width: 200px }
---

# Foo

Blah blah

![something](images/something.png)
```

**Comment by luckman212** [comment]
Thanks - that's useful! But I guess there's no way to control the size per-image? If I had 1 image that should be 200 and another 500, for example.

**Comment by simonhaenisch** [comment]
Just use an image tag instead of markdown syntax?

```
# Foo

Blah blah

<img src="images/something.png" alt="something" style="width:200px">
```

(you can mix html tags into your markdown)

Or you can be more specific with your css... `img:first-of-type { width: 200px } img:nth-of-type(2) { width: 500px }`.

**Comment by luckman212** [comment]
The problem with that is my markdown editor / vault ([Obsidian](https://obsidian.md/)) does not render `<img>` tags for local images. So, catch-22.
