### ISSUE TITLE
Question: Code Block highlighting

### ISSUE THREAD

**Issue by wilsonpg** [simonhaenisch/md-to-pdf#119]
Is there a usage example of this hiding on the internet somewhere?  It isn't working by default when using ``` to format my code blocks.

I tried using both the `highlight_styles` and the `highlight` function on the `marked_options`, to no avail.

Sorry for the question, I just haven't been able to find any other source that provides an answer on this.  I don't believe it's a bug, but I can't get it to work.

<img width="166" alt="image" src="https://user-images.githubusercontent.com/54870992/157467881-4cc45d29-2022-478e-889e-bea1d5227409.png">
<img width="166" alt="image" src="https://user-images.githubusercontent.com/54870992/157468306-b717bc27-b58d-419c-b2db-0b17dfb28fe2.png">
<img width="462" alt="image" src="https://user-images.githubusercontent.com/54870992/157467970-bbb4e8f5-ab00-468a-ba1a-968a1e0444b3.png">

**Comment by simonhaenisch** [comment]
Hey, you'd have to specify the language for the block manually, by appending it after the start of the fence, e. g.

<pre>```js
const foo = 'bar';
```</pre>

IIRC automatic language detection doesn't work here. Not sure how easy it would be to implement it, open to a PR though (:
