### ISSUE TITLE
Table conversion problem from '.md' to '.pdf' formats

### ISSUE THREAD

**Issue by abhi3700** [simonhaenisch/md-to-pdf#12]
Hello @simonhaenisch , 
           I am facing an issue.
## The sample in markdown file is as follows: - 
        ---
	stylesheet: https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.10.0/github-markdown.min.css
	body_class: markdown-body
	css: >-
	  .markdown-body { font-size: 11px; }
	  .markdown-body pre>code { white-space: pre-wrap; }
	---

	BJT | MOSFET
	----|-------
	Bipolar junction transitor | Metal Oxide Semiconductor <br/> Field effect transistor
	3 terminal - C, B, E | 4 terminal - S, G, D, B(body/substrate)
	for low current applicaions | high power applications
	less commonly used in A & D circuits | most commonly used 
	depends on current at base | depends on voltage at insulated oxide gate electrode
	replaced the old vacuum tubes | voltage controlled device
	cheap | costlier
	conduction is due to majority & minority carriers | only due to majority carriers

## Markdown preview
![markdown preview](https://user-images.githubusercontent.com/16472948/40429426-4d8be0d8-5ec0-11e8-8b83-b17ea3ae8162.png)

## PDF preview
![pdf preview](https://user-images.githubusercontent.com/16472948/40429478-6ba15f4e-5ec0-11e8-9f6a-4004458e7ec2.png)

## Problem statement
- the table in pdf format doesn't look identical to the one of markdown img.
- Is there any way to remove the css stylesheet entire statement (appearing along with the table) ?

Thanks,

Have a nice day :)

**Comment by simonhaenisch** [comment]
Please make sure the frontmatter is at the very start of your document, i. e. your document starts with the `—-` line and nothing before that. See [this link](https://jekyllrb.com/docs/frontmatter/) for how frontmatter works.

If that still doesn’t work, please pull the latest changes using `git pull` and reinstall using `npm i -g`.

**Comment by simonhaenisch** [comment]
Here is an example markdown file with your table and output pdf file: [example.zip](https://github.com/simonhaenisch/md-to-pdf/files/2033202/example.zip).

Hope that clarifies how to use it. I'll add some more info about how to use front-matter to the readme. Please let me know if you got it to work 🙌 .

**Comment by simonhaenisch** [comment]
a9b8eee82945d74c14a1f62e52194c91979ca519 adds some basic styling for tables (similar to github styles). Just `git pull` inside the cloned repo to get it onto your machine. Let me know if you still have issues with it.
