### ISSUE TITLE
bug: error when using glob pattern with no files found

### ISSUE THREAD

**Issue by kristiannotari** [simonhaenisch/md-to-pdf#132]
**Context:**

- version (`md-to-pdf -v`): 5.1.0
- platform (Unix, macOS, Windows): macOS (laptop) & ubuntu 20.04 (GitHub action)
- node version: 16.5.1 & 16.x

**Describe the bug:**

With the following command, when more glob pattern are used to target files, but one of them doesn't match any files, the conversion works for the found files and exit with an error when it doesn't find the others:
![1](https://user-images.githubusercontent.com/17885006/189368926-9d3476be-5f6e-46e5-84bb-f20f5c95cd54.png)

I'm using [globstar](https://www.npmjs.com/package/globstar) package for glob patterns, but the issue exists even when specifying non recursive glob patterns. Is there a way to have a "pass even if no files are matched" flag?

Minimal version:
![2](https://user-images.githubusercontent.com/17885006/189368983-44196b44-34c1-418a-a5db-30cdf56ef7d7.png)

**Comment by simonhaenisch** [comment]
Hey I would say that the issue is with globstar in that case, which seems to pass `"docs/**/*.md"` as a literal string if it doesn't find any files, i. e. doesn't expand the glob?

**Comment by simonhaenisch** [comment]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/3410759/189428420-a044b073-d9b0-4e5c-8e55-90bb45944fc3.png">

Looks like that's exactly what's happening 🤷🏻‍♂️

Just wondering, why can't you use normal shell glob expansion? Because you need it to be cross-platform?

**Comment by kristiannotari** [comment]
> 

Yeah I'm using it to ensure cross-platform correctness of npm commands. The command with globstar works correctly for other repo of mine where I do have some `.md` files target by those glob patterns. By the way, in my second screenshot, you can find a minimal version where even without globstar the md-to-pdf command fails with no files found for given pattern. Is there a way to have a "--pass-with-no-files" option?

**Comment by simonhaenisch** [comment]
No worries.

As a solution on your side, you can write a script and use a package like [globby](https://www.npmjs.com/package/globby) or [glob](https://www.npmjs.com/package/glob) yourself, i guess?

```js
import { execa } from 'execa'
import { globby } from 'globby'

const files = await globby(['docs/*.md'])

execa('md-to-pdf', ['--config-file', 'docs.config.js', ...files]).stdout.pipe(process.stdout)
```

(or use md-to-pdf's programmatic API but iirc it doesn't support parallelism with a shared browser instance yet, so it would be a bit slower).

Or you somehow test your glob for matches first and then conditionally call md-to-pdf only if files exist (not sure there's a good cross-platform solution for that).

**Comment by kristiannotari** [comment]
Thanks for the suggestions. I don't need to overcomplicate this, I'm doing all of this for docs related purposes, so the less scripts, logics and packages are involved the better. I'm just making sure there's at least an empty `.md` file as per documentation for each repo. No repo should contain 0 doc files anyway!!! 😄
