### ISSUE TITLE
bug: Markdown to PDF Code Injection

### ISSUE THREAD

**Issue by whlshy** [simonhaenisch/md-to-pdf#134]
**Context:**

- version (`md-to-pdf -v`): 5.1.0
- platform (Unix, macOS, Windows): Windows
- node version: v16.14.2

**Describe the bug:**

input text:
```markdown
<script>document.location="/"</script>
```

output file:
![image](https://user-images.githubusercontent.com/49122960/192451315-9f704c46-d5f0-4a38-8d2f-28e3b59cdbc7.png)

reference:
https://www.youtube.com/watch?v=QVaf4DMYPFc

**Comment by simonhaenisch** [comment]
Sanitizing user input is up to you.
