### ISSUE TITLE
Compile all markdown files in current directory if no arguments are given

### ISSUE THREAD

**Issue by simonhaenisch** [simonhaenisch/md-to-pdf#14]
If no arguments were given, instead of showing the help, search for all markdown (`*.md`, `*.markdown`, `*.mdown`, `*.md.txt`) files in the directory the command was invoked from, and compile each of them.

Maybe show a confirmation dialog if there are more than 10 files.

**Comment by simonhaenisch** [comment]
Closed in ef3763f.

**Comment by nekloth** [comment]
Can it be extend to "convert every MD in current folder and subfolder (if explicit parameter)"?

Plus exclusion parameter (or exclusion regex or exclulsion file)?

For instance : ```md2pdf --config conf.json . --exclude ["readme*.md", "changelog.md"]``` ... or similar?

**Comment by simonhaenisch** [comment]
I've been thinking about this yesterday, and would like to support it, but I had the following thoughts:

* The API would need a breaking change: at the moment, if there is two arguments, the second one is considered the output path (not sure if anyone actually uses that though); if we allow globs, e. g. `md2pdf *.md`, that would be expanded to an array of all the `.md` files in the `cwd`, and at the moment that would just take `args[0]` as the input and `args[1]` as the output.
* It's pretty straightforward to implement this until recursiveness (e. g. `md2pdf **/*.md`) is added: currently, the directory that the markdown files live in is served as a local http server, so that assets can be resolved as relative paths, e. g. `![](assets/my-image.png)`; when all markdown files live in the same folder, the same server can be used to render all files, but when recursively going through the file tree, the server would need to be restarted and serving a different directory every time the base dir changes.

**Comment by karlhorky** [comment]
As mentioned in #22, a workaround for this with the current version is a shell `for` loop:

```
{
  "scripts: {
    "build": "for file in dir/*.md; do md-to-pdf $file; done"
  }
}
```

Ref: https://github.com/karlhorky/npm-scripts-tricks/blob/master/readme.md#run-a-command-for-all-files-in-a-directory

**Comment by simonhaenisch** [comment]
@karlhorky if all files are in the same directory, you can even just do `md-to-pdf dir` :nerd_face: I'm actually planning to allow shell globbing so you can pass in a list of files, however it's going to be a breaking change and I want to do a few other things along with it.
