### ISSUE TITLE
question: add images to pdf

### ISSUE THREAD

**Issue by Fusted** [simonhaenisch/md-to-pdf#150]
**Problem:**

If I use mmd-to-pdf, the total pdf doesnt has images from md

**Comment by simonhaenisch** [comment]
Please check out the `--basedir` flag (see [usage](https://github.com/simonhaenisch/md-to-pdf#usage) in readme); image paths need to be relative to that directory which is `process.cwd()` by default (or absolute image paths should also work but it's less portable).

**Comment by flaviotordini** [comment]
Why the basedir flag? Shouldn't images always be resolved relative to the .md file? I can't see any other use case. This complicates the usage quite a bit.

**Comment by simonhaenisch** [comment]
Because it launches a server to host the files using the base dir as the root, but the md file is injected into the page like an "index.html" at the root path, thus paths being relative from the base dir.

I suppose it is a bit confusing, and could be solved in a different way where the source path of the markdown file is taken into account as well and the URL adjusted accordingly, but it's not that straightforward to implement, and would be a breaking change now.

**Comment by flaviotordini** [comment]
I tried

```
md-to-pdf ../path/to/my/doc.md
```
and images do not appear in the pdf.

Images are in the markdown are simply referenced like this:

```markdown
![](image.svg)
```

**Comment by simonhaenisch** [comment]
Ok, I think in this case the problem might just be that you're going up one directory with `..`. The http server as I said is launched from the base dir, which by default is `process.cwd()`, so any files outside your current working directory are not accessible from the server.

Can you try `md-to-pdf ../path/to/my/doc.md --basedir ..`?

**Comment by flaviotordini** [comment]
An absolute --basedir works. A relative one does not.

**Comment by simonhaenisch** [comment]
Published a fix so a relative `--basedir` should work as well. If you can give it a try with version `5.2.2`, please?

The limitation of not being able to reference relative files when navigating to files outside the current directory with `..` will persist though.

**Comment by flaviotordini** [comment]
Thanks, relative basedir works. I still think that having to specify basedir at all is an unneeded complexity.

**Comment by simonhaenisch** [comment]
How would you solve it? Using the file's dir name as the base dir by default? That would work in your case but prevent you from referencing images in parent folders which has been a common use case that would then require the base dir to be adjusted to the common directory of all images.

I guess one could first statically analyze all the image paths and automatically find the base path they all have in common. But you'd have to apply the same to scripts, stylesheets, etc. It's not worth the work for me when in at least 80% of the cases using `process.cwd()` as the base dir works fine. But feel free to open a PR (:

**Comment by flaviotordini** [comment]
Yes, I would make the markdown file dir the default. Think of any other document language, e.g. HTML: everybody is used to image paths relative to the doc path.

Images in another path could be resolved with a special frontmatter property:
```markdown
---
baseDir: /mypath
---
```

or with a template language, like usually done in HTML: 

```handlebars
[]({{baseDir}}/cat.jpg)
```

I understand this is breaking and should be withheld until a major version bump.

**Comment by simonhaenisch** [comment]
> Think of any other document language, e.g. HTML

It actually works exactly like in HTML now... the base dir is like the root folder of your server. The reason for it being `cwd` by default and not the markdown file's dir is that it covers more use cases.

Example:

```
project/
├── images/
│   └── foo.jpg
└── docs/
    └── file.md # references ../images/foo.jpg
```

If you run `md-to-pdf docs/file.md` from the project root and it assumed `docs` as the base dir, the `images` folder wouldn't end up being hosted by the file server and thus it wouldn't be able to render the image.

What you did with a path that goes up to the parent folder of `cwd` first is kind of an edge case in which manually specifying `--basedir` is then required. It doesn't make sense to make the more common use case require the `--basedir` flag.
