### ISSUE TITLE
--config option does not accept relative path

### ISSUE THREAD

**Issue by Zivaga** [simonhaenisch/md-to-pdf#19]
Hello

I have a doc repo structure like:
```
RepoFolderRoot
├───doc1
│       doc1.md
│       doc1.pdf
│
├───doc2
│   │   doc2.md
│   │   doc2.pdf
│
├───generate_pdf
│   │   config.json
│   │   mystyle.css
 ```

I tried to launch the md2pdf command from the root folder (for scripting) by trying:
```md2pdf --config-file .\generate-pdf\config.json .\doc1\doc1.md```
or
```md2pdf --config-file generate-pdf\config.json .\doc1\doc1.md```
or
```md2pdf --config-file \generate-pdf\config.json .\doc1\doc1.md```

And I always got a```Warning: couldn't read config file: \generate-pdf\config.json```

**Comment by simonhaenisch** [comment]
The related code is here:

https://github.com/simonhaenisch/md-to-pdf/blob/b83e9f1630078a14d17b1a0d7c28afbb10c4f6ee/index.js#L83-L90

I don't have access to a Windows machine right now, I'll look into it when I get access to one. Anyway, I'm not sure why [`path.resolve()`](https://nodejs.org/docs/latest/api/path.html#path_path_resolve_paths) would not work here... it's just supposed to take the relative path and make it absolute, relative to the current working directory.

Can you try running this in your directory and see if it works (i. e. prints your config), please:

```
node -e "console.log(require(path.resolve('generate-pdf\config.json')))"
```

**Comment by Zivaga** [comment]
Shame on me... I mistyped the folder (```generate-pdf``` instead of ```generate_pdf``` .... dash/underscore issue).

In fact, it works like a charm!

I'm really sorry for the not-real-issue.... (the issue where between the chair and the keyboard...) :-/

**Comment by simonhaenisch** [comment]
No worries, glad you could figure it out :nerd_face: I haven't thoroughly tested all the different options myself and only on macOS, so I'm thankful for any feedback on potential issues. Gives me a chance to improve the code :wink:

**Comment by Zivaga** [comment]
:) Sure. I will use it in a more scripted way very soon. If I think about ant improvement, I'll let you know.

Thanks!

**Comment by nekloth** [comment]
Hi

The relative path changed... it used to consider the relative path from the execution path, now, it considers relative path from the MD file.


It used to work with:
```
  "stylesheet": [
    ".\\mystyle.css"
  ],

```
when executed from c:\RepoFolderRoot\

Error is:
```
 md2pdf --config-file .\generate_pdf\config.json ./doc1/doc1.md
  × generating PDF from ./doc1/doc1.md
    → ENOENT: no such file or directory, open 'c:\RepoFolderRoot\doc1\mystyle.css'
```

and now works with...
```
  "stylesheet": [
    "C:\\RepoFolderRoot\\generate_pdf\\mystyle.css"
  ],
```

It is not very convenient for me, as my stylesheet lifecyle is different from doc lifecycle, and I'm not the only one to use this repo (and of course, all of us do not have the same folder organisation....)
