### ISSUE TITLE
Supporting Solidity code in markdown

### ISSUE THREAD

**Issue by csurbier** [simonhaenisch/md-to-pdf#191]
Hi,

I don't find how to support the Solidity language code in my markdown with your tool.

https://github.com/highlightjs/highlightjs-solidity

Can anyone help me ? 
Thanks
Christophe

**Comment by simonhaenisch** [comment]
Hi Christophe,

highlightjs is already included by default, but the solidity support script you'll have to load manually. You can do this by adding downloading `solidity.min.js` and adding it as a script to the config, e.g. via the front-matter:

````markdown
---
script:
  - path: /path/to/solidity.min.js
---

<!-- not sure about the language name tbh -->
```solidity
(some code here)
```

````

Let me know if this doesn't work then I can reopen the ticket.

**Comment by csurbier** [comment]
Can you confirm me that i'm doing correctly.
I have the **solidity.min.js** file here : 
/Users/christophesurbier/Dropbox/Christophe/Autonomo/Publishing/solidity_real/solidity.min.js
and here is my file markdown [:eBook](https://www.idevotion.fr/fullBook.md)

But when i'm launching the command: 
**cat fullBook.md  | md-to-pdf  > ebook.pdf** 

The PDF doesn't have the solidity code highlighted :(
 
Thanks a lot

**Comment by csurbier** [comment]
Just see in the highlight-solidity.js package this 
**Compatibility
This package is not currently compatible with highlight.js version 11.**
and in their package.json
"devDependencies": {
    **"highlightjs": "^9.12.0",**
    "mocha": "^6.2.1",
    "parse5": "^5.1.0"
  }

So added this to my markdown file: 

<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
<script src="/Users/christophesurbier/Dropbox/Christophe/Autonomo/Publishing/solidity_real/solidity.min.js"></script>
<script type="text/javascript">
    hljs.highlightAll();
</script>

but still not working :(
