### ISSUE TITLE
Header and footer management

### ISSUE THREAD

**Issue by nekloth** [simonhaenisch/md-to-pdf#2]
Is it possible to implement header and footer ?

The need is to have a footer/header for first page and another footer/header for the rest of the document, with the possibility to include page number.

(I saw this kind of feature in project node-html-pdf (https://github.com/marcbachmann/node-html-pdf).

**Comment by simonhaenisch** [comment]
I would definitely like that, but haven't had a look at it yet. The project you linked is the one I use here, so it might be possible to just use the `pageHeader`/`pageFooter` id as explained here:

<https://github.com/marcbachmann/node-html-pdf#footers-and-headers>

i. e., add the following to the top of your markdown file:

```html
<div id="pageHeader">Default header</div>
<div id="pageHeader-first">Header on first page</div>
```

BTW, I was also thinking of a simple way to cite and have a list of references at the end of the document... so far I've been pushing a numbered list down to the end of the last page like this:

```markdown
Lorem ipsum... [1].

<div style="height: 15em;"></div>

---

1. Author. Year. _Title_. Publisher.
2. ...
```

**Comment by nekloth** [comment]
Great!

Having footer, header and citation would definitely be useful!

**Comment by simonhaenisch** [comment]
Let me know if the `pageHeader`/`pageFooter` ids worked for you, please 🤓

**Comment by nekloth** [comment]
Looks good !
![image](https://user-images.githubusercontent.com/4066135/31717871-02e862fc-b40e-11e7-8df3-ac6e33dcd329.png)

I tested using ```<div id="pageFooter" style="text-align:center">Page {{page}} on {{pages}}</div>```:
![image](https://user-images.githubusercontent.com/4066135/31717981-6dc54fae-b40e-11e7-8ac3-98279798fcbf.png)

That's seems to be okay. Good job !

**Comment by simonhaenisch** [comment]
Thanks, will add that to the readme
