### ISSUE TITLE
Path to highlight.js css files is wrong

### ISSUE THREAD

**Issue by marcuslindfeldt** [simonhaenisch/md-to-pdf#21]
When installing md-to-pdf as a dev dependency in another project the path to the highlight.js css files will no longer be relative to /md-to-pdf/.

```
(node:52783) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/path/to/other-project/node_modules/md-to-pdf/node_modules/highlight.js/styles/monokai.css'
  -- ASYNC --
...
```

In other words the path:

```
/path/to/other-project/node_modules/md-to-pdf/node_modules/highlight.js/styles/monokai.css
```

should in this case be:

```
/path/to/other-project/node_modules/highlight.js/styles/monokai.css
```

**Comment by simonhaenisch** [comment]
Ok, thanks for the issue, will get that fixed and publish a new release within the next hour.

**Comment by simonhaenisch** [comment]
Just published, should be on npm within a couple minutes :nerd_face:

**Comment by simonhaenisch** [comment]
@marcuslindfeldt I added a programmatic API yesterday... thought I'd let you know in case you're still using this within your project, because that should be more convenient than spawning processes :nerd_face:

See https://github.com/simonhaenisch/md-to-pdf/releases/tag/v2.5.0.

**Comment by codingwithdidem** [comment]
Hello I'm getting the same error when deploying on vercel 


<img width="886" alt="Screen Shot 2022-04-17 at 14 20 50" src="https://user-images.githubusercontent.com/78794523/163712196-2d8db13e-3835-452e-b2a9-ea11604ef5f0.png">

**Comment by FelipeJz** [comment]
> Hello I'm getting the same error when deploying on vercel
> 
> <img alt="Screen Shot 2022-04-17 at 14 20 50" width="886" src="https://user-images.githubusercontent.com/78794523/163712196-2d8db13e-3835-452e-b2a9-ea11604ef5f0.png">

I'm having a similar issue when using Next, any ideas?

**Comment by simonhaenisch** [comment]
Just a guess maybe you have `highlight.js` and/or `md-to-pdf` as dev dependencies so Vercel skips installing them? Otherwise no idea.
