### ISSUE TITLE
Allow to pass multiple input files via globbing

### ISSUE THREAD

**Issue by simonhaenisch** [simonhaenisch/md-to-pdf#22]
Following some discussion on issue #14, I would like to change the API to allow to pass multiple input files via shell globbing. This will be a breaking change because currently the second input argument is treated as the pdf output filename.

```shell
$ md-to-pdf **/*.md
```

The shell would expand the glob into an array of files that will be passed as input arguments (leaving the glob expansion to the shell rather than dealing with it using some npm package).

**Comment by karlhorky** [comment]
To do this with the current version, you can do this with a shell `for` loop in your npm script:

```
{
  "scripts: {
    "build": "for file in dir/*.md; do md-to-pdf $file; done"
  }
}
```

Ref: https://github.com/karlhorky/npm-scripts-tricks/blob/master/readme.md#run-a-command-for-all-files-in-a-directory

**Comment by simonhaenisch** [comment]
Ah, I see you had already found this issue! Thanks for dropping the info here (:

**Comment by dej611** [comment]
Similar use case, but for massive amount of pdfs: the approach above didn't scale for me (~8000 pdfs from markdown), it took 2 hours just to make 1000 pdfs and I had 7000 more to go.

I know it's an edge case.

I thought to share the thing here in case someone is facing a similar problem.
At first I tried to look into the renderer library itself and make it scale on concurrency or maybe let puppeteer manage tabs to render in batches. The thing didn't work well and it required a lot of effort to make a prototype.

So I flipped the logic, based on a strong assumption that maybe not everybody can do: I did know how big, in terms of pages, is each markdown document when in PDF and the layout style was always the same. In my case 1 page in PDF = 1 markdown.
The approach was as follow;
* create a single, giant, markdown file. The style will be applied only once on top.
* save as JSON file the mapping information about the order of the markdown document, for later.
* apply `md-to-pdf` to the giant markdown file. It took roughly 2 minutes.
* install the `qpdf` tool and use it from the CLI to split the PDF into multiple files:
  ```js
  qpdf in.pdf out.pdf --split-pages
  ```
  The command above will create N `out-00N.pdf` files, one per page. It took roughly 30 minutes.
* Use the `json` file with the mapping to rename thee final files. Few seconds.

Hope this helps.

**Comment by karlhorky** [comment]
Nice workaround @dej611 :) 

If anyone would also have a massive amount of Markdown files but different requirements such as having content longer than one page or different styles (or still want one step in an npm script), they could consider doing these via `npm-run-all` (specifically, the [`runp` command](https://github.com/mysticatea/npm-run-all/blob/master/docs/run-p.md#npm-scripts)).

Not sure if that would achieve the performance you're looking for, but it would speed things up somewhat.

**Comment by simonhaenisch** [comment]
There's two approaches I can think of for making this fast:

- Reuse the same page (tab) for each file
- Create one tab for each file

I'm not sure about the limits of concurrency of the `page.pdf()` method of Puppeteer, whether it can run multiple pdf conversions simultaneously for different tabs. I'll see whether I can experiment which one works better.

Concurrency is already possible with the current version (if all files are in the same folder), but it launches a new window for each file which has a big overhead per file and that's probably why it's slow.

**Comment by dej611** [comment]
@karlhorky I used a similar approach to the `npm-run-all` and this was the speed:
> Similar use case, but for massive amount of pdfs: the approach above didn't scale for me (~8000 pdfs from markdown), **it took 2 hours just to make 1000 pdfs** and I had 7000 more to go.

The bottleneck wasn't the disk I/O as the PDF split was way faster.

Perhaps another approach could be to create a massive HTML page from all the markdowns, handling styles and pages mapping properly, create a single PDF and splitting it using the mapping.
