### ISSUE TITLE
feature: Support for footnote, as Github-Flavored-Markdown now supports footnote

### ISSUE THREAD

**Issue by snawaz** [simonhaenisch/md-to-pdf#221]
It seems footnote isn't supported yet. 

https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/

**Comment by simonhaenisch** [comment]
Please raise this request in https://github.com/markedjs/marked or check if there's already an issue for it. This tool doesn't implement any markdown parsing by itself, it just uses Marked to convert it.
