### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by PinkPanther-ny** [simonhaenisch/md-to-pdf#277]
**Context:**

- version (`md-to-pdf -v`): 5.2.4
- platform (Unix, macOS, Windows): all
- node version: all

**Describe the bug:**
Chinese characters not supported.
![issue](https://github.com/simonhaenisch/md-to-pdf/assets/68553531/7510ce55-68fc-4f75-a239-6ab493dac1a8)

**Comment by simonhaenisch** [comment]
Looks like you're missing a Chinese font. See https://github.com/simonhaenisch/md-to-pdf/issues/110#issuecomment-1094464809
