### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by lorenzo-arena** [simonhaenisch/md-to-pdf#3]
Hi, 
I'm having problems using "windows1252" as default markdown files encoding. 

Whenever I use accented chars  they became unknown chars when I try to convert the markdown file to pdf.

- here's the screenshot of the editor and the preview:

![test_1](https://user-images.githubusercontent.com/22166510/33167190-034545da-d03d-11e7-865d-f93bed2665a9.PNG)

- and here a screen of the converted pdf:

![test_3](https://user-images.githubusercontent.com/22166510/33167209-158d34b4-d03d-11e7-871e-6ccc92f37d57.PNG)

Is there a way (maybe some css style file to edit) to change the output encoding so they match?

**Comment by simonhaenisch** [comment]
yes there is, just set the encoding to `windows1252` in `config.js`:

https://github.com/simonhaenisch/md-to-pdf/blob/7ef10be64097a95b383d64b7f894b6709800c53c/config.js#L14

I'm working on implementing command line options to make this tool more configurable (:

**Comment by simonhaenisch** [comment]
So, [according to this](https://stackoverflow.com/a/14551669/2897426) Node.js doesn't natively support `windows1252`, but in the latest commit (1f98c827cbd9009936f4208e67700516e808fbbf) I added decoding. Try again with that one please, and also note that you can change file encoding separately now for css and markdown. Let me know if you have issues :)

**Comment by lorenzo-arena** [comment]
Everything seems to be ok, so thank you 👍
