### ISSUE TITLE
Stylesheet paths are not relative to the file they are in

### ISSUE THREAD

**Issue by simonhaenisch** [simonhaenisch/md-to-pdf#37]
Hi

The relative path changed... it used to consider the relative path from the execution path, now, it considers relative path from the MD file.

It used to work with:
```
  "stylesheet": [
    ".\\mystyle.css"
  ],

```
when executed from c:\RepoFolderRoot\

Error is:
```
 md2pdf --config-file .\generate_pdf\config.json ./doc1/doc1.md
  × generating PDF from ./doc1/doc1.md
    → ENOENT: no such file or directory, open 'c:\RepoFolderRoot\doc1\mystyle.css'
```

and now works with...
```
  "stylesheet": [
    "C:\\RepoFolderRoot\\generate_pdf\\mystyle.css"
  ],
```

It is not very convenient for me, as my stylesheet lifecyle is different from doc lifecycle, and I'm not the only one to use this repo (and of course, all of us do not have the same folder organisation....)

_Originally posted by @nekloth in https://github.com/simonhaenisch/md-to-pdf/issues/19#issuecomment-500891206_

**Comment by simonhaenisch** [comment]
@nekloth thanks for bringing this up, I think you're right that this is confusing... should probably resolve paths relative to the file they are in.

**Comment by nekloth** [comment]
In fact, it depends what file are you talking about :) Config file or md
file?

Le mer. 12 juin 2019 à 09:57, Simon Hänisch <notifications@github.com> a
écrit :

**Comment by simonhaenisch** [comment]
Well, I'm thinking if you're specifying a relative path:

- in the config file, it should be relative to that config file 
- in the frontmatter of the md file, it should be relative to the md file
- in the cli, it should be relative to the process cwd

**Comment by nekloth** [comment]
:) Sounds good and generic enough to satisfy lot of different use cases!
