### ISSUE TITLE
bug: SyntaxError Unexpected token function

### ISSUE THREAD

**Issue by salmonjean** [simonhaenisch/md-to-pdf#38]
**Context:**

- version (`md-to-pdf -v`): 2.7.1
- platform (Unix, macOS, Windows): Debian 8.11 64-bit
- node version: 6.17.1

**Describe the bug:**
(A clear and concise description of what the bug is. Feel free to include screenshots.)

Dear Support Team,

After installed successfully "md-to-pdf" on Debian 8.11, I’ve tried to convert my first markdown file in pdf.
Unfortunately, I encountered this error message :

![md-top-pdf - SyntaxError Unexpected token function](https://user-images.githubusercontent.com/53435419/62129480-1b76e400-b2d7-11e9-9e4f-7936cc362b79.jpg)

Thanks for your help.

Regards,

Jean Salmon

**Comment by kleyu** [comment]
Looks like `md-to-pdf` requires   "node": ">= 8.3.0".
https://github.com/simonhaenisch/md-to-pdf/blob/46d2fe54df7d0f511c0a7370e2143f08a72a734d/package.json#L18

Have you tried updating your node.js version?

**Comment by salmonjean** [comment]
Hi Jakub,
Thanks to have replied so quickly!
I've upgraded node.js up to 8.16.0. 
![image](https://user-images.githubusercontent.com/53435419/62132217-ebcada80-b2dc-11e9-8348-04d91f7207e8.png)

Now I have a new error message.
![md-top-pdf - Troubleshooting puppeteer](https://user-images.githubusercontent.com/53435419/62132261-01d89b00-b2dd-11e9-9731-e5c55f674bf5.jpg)

I hope the weather is fine in Poland! ;-)

**Comment by kleyu** [comment]
Hey @salmonjean 
Have you tried following the instructions in the error message? I believe it would point you somewhere here: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

Puppeteer (the headless chrome driver used in this module) has some dependencies that are needed to run it, especially when it comes to UNIX based systems. Try installing them using the troubleshooting link [here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix), or [this](https://github.com/GoogleChrome/puppeteer/issues/290) thread if installing the required dependencies still doesn't resolve the issue.

**Comment by simonhaenisch** [comment]
Hey @salmonjean, yes that first error was because Node v6 does not support the async/await syntax yet.

Regarding the second error, can you check whether you have all the dependencies required for Debian installed? See https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix.

It might also be a sandboxing issue, in which case you can try disabling the sandbox by running the tool with the following flag:

```
md-to-pdf --launch-options '{ "args": ["--no-sandbox", "--disable-setuid-sandbox"] }'
```

**Comment by salmonjean** [comment]
Hi Simon ! Hi Jakub !
It works! :-)

![image](https://user-images.githubusercontent.com/53435419/62135561-b923e080-b2e2-11e9-99ce-4205105fa0fd.png)

Thank you for your help to both of you
