### ISSUE TITLE
SyntaxError in index.js

### ISSUE THREAD

**Issue by lorenzo-arena** [simonhaenisch/md-to-pdf#4]
I'm having trouble trying to convert any document.

Everytime I get this exception:

![error](https://user-images.githubusercontent.com/22166510/33380607-f9840d0e-d51b-11e7-9103-647740876eca.png)

This happens even if my cloned repo is clean.

**Comment by simonhaenisch** [comment]
Which Node version are you using? I started using some of the newer ES syntax... works fine for me on `v8.9.1` (on macOS, with a `windows-1252` encoded file).

**Comment by lorenzo-arena** [comment]
I was using v6.11.2, upgraded to v8.9.1 and now I get:

![error_2](https://user-images.githubusercontent.com/22166510/33421239-b3ea53d4-d5b1-11e7-919d-58fc7dc97102.png)

**Comment by simonhaenisch** [comment]
You need to run `npm i -g` inside the `md-to-pdf` directory again to install that module, because I changed the dependencies in the latest commit.

**Comment by lorenzo-arena** [comment]
Thank you again, everything's ok now :smiley:
