### ISSUE TITLE
bug: impossible to set color background in header/footer

### ISSUE THREAD

**Issue by salmonjean** [simonhaenisch/md-to-pdf#43]
Hi Simon !

I'm not able to specify a color background in header or footer.

I saw this issue for puppeteer : "cannot add background color to Header/Footer".
https://github.com/GoogleChrome/puppeteer/issues/2182

Did you already have encountered this problem ?

Regards,

Jean

**Comment by simonhaenisch** [comment]
Have you set `printBackground: true` in the pdf options?

**Comment by salmonjean** [comment]
Yes, the option _printBackground: true_ is well set in pdf_options subset.
I've also added _webkit_print_color_adjust: "exact"_ without success :-(

This is just a part of my js code :

```
(…)
const options = {
	stylesheet: "my-stylesheet.css",
	md_file_encoding: 'utf-8',
	pdf_options: {
	 printBackground: true,
	 format: 'A4',
	 margin: {
	   top: '20mm',
	   right: '10mm',
	   bottom: '27mm',
	   left: '10mm',
	 },
	 displayHeaderFooter: true,
	 headerTemplate: templates.headerTemplate,
	 footerTemplate: templates.footerTemplate,
	 webkit_print_color_adjust: "exact"
	},
	'launch-options': {
		args: ["--no-sandbox", "--disable-setuid-sandbox"]
	},
(…)
```

**Comment by simonhaenisch** [comment]
Ok, it's probably something that's not supposed to work as of yet according to the CSS spec for pages. However you can "hack" it together with a couple tricks.

First, go to http://png-pixel.com to get a 1x1 pixel image with your desired color as a data url (probably you'll want to set opacity to 1). Then put that image tag into your template, and style it.

```html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8f5XhPwAHhALVcCjBxgAAAABJRU5ErkJggg==">
```

```css
img {
  position: absolute;
  top: 0;
  width: 100%;
  height: 20mm; /* adjust according to your top page margin */
  z-index: -1;
}
```

---

Here's an example front-matter from the test file:


```yaml
pdf_options:
  format: A4
  margin: 30mm 25mm
  displayHeaderFooter: true
  headerTemplate: >-
    <style>
      section { font-size: 11px; width: 100%; text-align: center; }
      img { position: absolute; top: 0; width: 100%; height: 20mm; z-index: -1; }
    </style>
    <section>Header</section>
    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8f5XhPwAHhALVcCjBxgAAAABJRU5ErkJggg==">
  footerTemplate: >-
    <section>
      Page <span class="pageNumber"></span>
      of <span class="totalPages"></span>
    </section>
```

![image](https://user-images.githubusercontent.com/3410759/63445726-300f4d80-c439-11e9-85bb-43f1aa1a2cfb.png)

**Comment by salmonjean** [comment]
Hi Simon !

Thanks for the workaround nevertheless I have a bigger problem than the background color.
I'm using your tool on several markdown files. 
I need to be able to change some parts of the header according to one parameter.
For each md file, I have to set the header with the chapter title.
In order to call to modify the Template for each  md file ; I've tried to use a function treated like a class but it doesn't work :
module.exports = function (numChapter) {  
	headerTemplate: 
Header and Footer displayed are thems by default.

**Comment by salmonjean** [comment]
Hi Simon !

Thanks for the workaround nevertheless I have a bigger problem than the background color.
I'm using your tool on several markdown files.
I need to be able to change some parts of the header according to one parameter.

For each md file, I have to set the header with the chapter title.
In order to set the template for each md file ; I've tried to use a function "treated like a class" but it doesn't work :

 module.exports = function (numChapter) { 
        (…)

Header and Footer displayed are thems by default.

Do you have an idea?

**Comment by salmonjean** [comment]
Hi Simon !
Thanks for the workaround nevertheless I have a bigger problem than the background color.
I'm using your tool on several markdown files.
I need to be able to change some parts of the header according to one parameter.
For each md file, I have to set the header with the chapter title.
In order to set the template for each md file ; I've tried to use a function "treated like a class" but it doesn't work :
module.exports = function (numChapter) {
(…)
Header and Footer displayed are the default ones.
Do you have an idea?

**Comment by simonhaenisch** [comment]
Well, as you have already found out, it's not really possible with Puppeteer, so there's nothing I can do about it.

Just look through the linked issues whether you can find a hack to work around it... e. g. I found this one which looks promising: https://github.com/GoogleChrome/puppeteer/issues/2167#issuecomment-425448926. He adds an image tag into the header and injects a script into the `onload` attribute of that image tag, to run stuff.

**Comment by salmonjean** [comment]
OK Simon. Thanks for you answer.
