### ISSUE TITLE
bug: not all css applied (background-color)

### ISSUE THREAD

**Issue by Prowluan** [simonhaenisch/md-to-pdf#49]
I'm trying to generate a pdf using the config file, with a css file, but not all CSS is applied. It does not generate an error on the config.

- version (`md-to-pdf -v`): 2.7.1
- platform (Unix, macOS, Windows): windows
- node version: v8.12.0

When I generate a pdf using config, which contains header and footer content and a css file, the generated pdf does not have all css applied. Below I have applied 2 screenshots; one containing how it should look (this does not use a config file, using a css file), and one how it looks with the config file, using a css file.

My config file looks like this:

{
  "pdf_options": {
    "format": "A4",
    "margin": "20mm",
    "displayHeaderFooter": false
  },
  "stylesheet": "style.css"  
}

Any idea why the css is not applied as I want it to?

![case1](https://user-images.githubusercontent.com/57523191/68466038-e8b48400-0213-11ea-940c-9226e66ed656.png)
![case2](https://user-images.githubusercontent.com/57523191/68466047-ece0a180-0213-11ea-9fce-39c1f635705f.png)

**Comment by simonhaenisch** [comment]
Hey, sorry for the late reply. I assume that the problem is that you don't have `"printBackground": true` set in your pdf options... could you try that and let me know if it worked? Thanks!

**Comment by Prowluan** [comment]
Works like a charm, thanks!

**Comment by simonhaenisch** [comment]
I actually detected a bug regarding this... if you use the frontmatter for the config, then `printBackground` will be set to true by default, even if you provide your own `pdf_options`. However the behavior isn't the same if you use the config file instead. This has been fixed in v3 which I hope to release soon.
