### ISSUE TITLE
bug: config.json conflict when both highlight_style and pdf_options

### ISSUE THREAD

**Issue by pawelkuras** [simonhaenisch/md-to-pdf#50]
**Context:**

- version (`md-to-pdf -v`): 2.8.1
- platform (Unix, macOS, Windows): Windows 10
- node version: 13.1.0

**Describe the bug:**

If you have both the **highlight_style** and **pdf_options** in a config.json file, the highlighting doesn't quite work.  With styles like "monokai" and "darcula" the background should be black, but this is completely lost.  Sample config.json that won't work:
```
{
  "highlight_style": "darcula",
  "pdf_options": {
    "format": "Letter",
    "margin": "10mm"
  }
}
```

But the following will work:
```
{
  "highlight_style": "darcula"
}
```

**Comment by simonhaenisch** [comment]
Ha, this one got me pretty confused at first 😄 But actually it's not a bug, it's just that in the default `pdf_options`, there is `"printBackground": true`.

So with the following config it should work:

```json
{
  "highlight_style": "darcula",
  "pdf_options": {
    "format": "Letter",
    "margin": "10mm",
    "printBackground": true
  }
}
```

Thanks for the detailed description 👍 I'll put sth in the readme to make it more clear that this option needs to be set wrt highlighting.

**Comment by pawelkuras** [comment]
Glad it was that straightforward.  Thanks @simonhaenisch.

I see now that it uses Puppeteer to convert html to pdf, and the pdf_options map to [Puppeteer's page.pdf([options])](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions)
