### ISSUE TITLE
example for js config file

### ISSUE THREAD

**Issue by pawelkuras** [simonhaenisch/md-to-pdf#51]
Can you please add an example of a js config file in the readme.  I tried to export a default object and had no luck.

**Comment by simonhaenisch** [comment]
I've actually already done that on the v3 branch (see https://github.com/simonhaenisch/md-to-pdf/tree/v3#options):

```js
module.exports = {
  stylesheet: [
    "path/to/style.css",
    "https://example.org/stylesheet.css",
  ],
  css: `body { color: tomato; }`,
  body_class: "markdown-body",
  marked_options: {
    headerIds: false,
    smartypants: true,
  },
  pdf_options: {
    format: "A5",
    margin: "20mm",
    printBackground: true
  },
  stylesheet_encoding: "utf-8",
};
```

**Comment by simonhaenisch** [comment]
Oh, I see, it's not a default exported object, but just an exported object. I'll fix the readme.

**Comment by pawelkuras** [comment]
that worked, thanks @simonhaenisch
