### ISSUE TITLE
Funding for md-to-pdf

### ISSUE THREAD

**Issue by chrisvxd** [simonhaenisch/md-to-pdf#53]
Hey @simonhaenisch! 👋

Just wanted to reach out about funding your work on `md-to-pdf`.

@transitive-bullshit and I are both open source maintainers, and we're currently exploring new ways to make OSS funding a viable source of income.

We're currently looking at building SaaS APIs on top of existing OSS libraries, reserving the majority of profits for the original authors. [We've built a few](https://saasify.sh/#/showcase) at this point, but want to keep adding more.

I think `md-to-pdf` could make a really handy SaaS API, and I'd love to build one out. We'd handle dev, auth, billing and support so you wouldn't have to do anything.

Looking forward to hearing your thoughts! 🙏

**Comment by simonhaenisch** [comment]
Thanks Chris, sounds like an interesting business idea you have there. I'm actually still working on v3 of this project, in which I'm trying to simplify the API a bit more wrt converting multiple files at once. Other than that the API should mainly stay the same, so yeah you can give it a go. Is there anything you need from me?

**Comment by chrisvxd** [comment]
Thanks for getting back to me!

Good to know, will keep an eye on the `v3` branch.

I think that should be everything at this point, but we can discuss things as we go via this thread  :)

**Comment by chrisvxd** [comment]
P.S. if you want a more direct line of communication, we have [an open slack](https://join.slack.com/t/saasify/shared_invite/enQtODAxODA5MzU0NjczLTczOGU3NzNkYTJlMWIwZDkyNjJkOTk3MGEwZThlOWQyNTQxODZjZTExNjAzODJlZDQ3MWM5NWQwMGRiMDcyZTY)

**Comment by simonhaenisch** [comment]
Hi again, I've been working a bit more on version 3 but it's taking me longer than expected (there's some design decisions to be done that i wasn't anticipating). So feel free to go ahead with the current version, the API will likely not change much anyway.

**Comment by simonhaenisch** [comment]
@chrisvxd there's a pre-release of v3 now, if you're still interested in using this for your platform.

**Comment by chrisvxd** [comment]
Hey @simonhaenisch - I'm so sorry that I never got back to you. I am no longer working on Saasify full-time, and must have missed your messages.

Saasify now has a marketing page (http://saasify.sh) and I reckon you could convert this into a SaaS product pretty easily, but unfortunately I'd now be unable to do convert it myself. If you're interested, I can definitely get you access to the self-serve beta so let me know!

Happy to keep chatting [via slack](http://saasify.slack.com) if you want (I see you're already on there). If not, apologies again for not responding and good luck!

Awesome work getting v3 out the door!

CC @transitive-bullshit
