### ISSUE TITLE
bug: Anchor links doesn't work when it written by multibytes chars

### ISSUE THREAD

**Issue by advancedbear** [simonhaenisch/md-to-pdf#58]
**Context:**

- version (`md-to-pdf -v`): 2.8.2
- platform (Unix, macOS, Windows): Windows
- node version: 8.11.3

**Describe the bug:**

Anchor links doesn't work.

I wrote following basic markdown and convert it to pdf.
```
- [Anchor1](#anchor1)
- [Anchor 2](#anchor-2)
- [アンカー3](#%E3%82%A2%E3%83%B3%E3%82%AB%E3%83%BC3)
- [アンカー 4](#%E3%82%A2%E3%83%B3%E3%82%AB%E3%83%BC-4)

# Anchor1
ASCII chars and no blank.

# Anchor 2
ASCII chars and blank.

# アンカー3
Japanese chars and no blank.

# アンカー 4
Japanese chars and blank.
```

`Anchor1` and `Anchor 2` works well as I expected, but `アンカー3` and `アンカー 4` doesn't convert as link. 

When I hover the cursor on `アンカー3` and `アンカー 4` in the output PDF, the cursor doesn't change as finger pointer.
But when I output html with `--as-html` option, the links works fine. \<a\>tag is perfectly works in Chrome browser.

Please give me any advise for this problem.

Thanks.

**Comment by simonhaenisch** [comment]
> But when I output html with `--as-html` option, the links works fine. <a>tag is perfectly works in Chrome browser.

You can confirm the same when running with `--devtools`. After that the [`page.pdf()`](https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-pagepdfoptions) method of Puppeteer is called to generate the PDF, so something must be going wrong in that step. Therefore would you please open an issue in the upstream repository [puppeteer/puppeteer](https://github.com/puppeteer/puppeteer)? You can link to this one for context.

**Comment by simonhaenisch** [comment]
If you need a work-around in the meantime, you can extend the Marked renderer to generate your own heading ids and avoid/replace special characters. The docs are at https://marked.js.org/#/USING_PRO.md#renderer, and you have to make a `config.js` file:

```js
const { Renderer } = require('marked');

const renderer = new Renderer();

renderer.heading = (text, level) =>
  `<h${level} id="${injectSomethingHere}">${text}</h${level}>`;

module.exports = { marked_options: { renderer } };
