### ISSUE TITLE
bug: config-file CLI option does not work

### ISSUE THREAD

**Issue by ltfschoen** [simonhaenisch/md-to-pdf#60]
**Context:**

- version (`md-to-pdf -v`): 2.8.2
- platform (Unix, macOS, Windows): macOS
- node version: v13.3.0

**Describe the bug:**

When I run the following, it always says gives error `Warning: couldn't read config file: ./config.json`, even if a config.json file is in the current directory.

```
md-to-pdf ./README.md \
  --config-file ./config.json \
  ./output.pdf
```

When I check help it says it wants me to specify a "Path"
```
 --config-file ............ Path to a JSON or JS configuration file
```

But if I provide the "Path" (i.e. `./` which is the current directory) instead, I get the same error:

```
md-to-pdf ./README.md \
  --config-file ./ \
  ./output.pdf
```

**Comment by ltfschoen** [comment]
Closing, it wasn't working because my JSON was invalid (i.e. unnecessary comma), not because it couldn't find the file (even though the error said it couldn't find it

**Comment by simonhaenisch** [comment]
It says it couldn't **read** the file which can also mean unreadable in the sense of not parseable. I think if you add the `--debug` flag, you could have seen the exact error. But thanks for mentioning it, I'll try to add some better error messages there (:
