### ISSUE TITLE
Question: Images in PDF are split across multiple pages

### ISSUE THREAD

**Issue by ltfschoen** [simonhaenisch/md-to-pdf#61]
When I generate a PDF from a markdown file, some images are split and appear across multiple pages. Is it possible for it to only show an image on a single page?

**Comment by simonhaenisch** [comment]
It's up to you to do the styling for that. You can write some custom css that adds a page break (`page-break-after: always;`) to your images and limits the height using e. g. `max-height`. I'm not sure there's a way to automatically get the page height though, but you could infer it from the page format (minus margins).

**Comment by ltfschoen** [comment]
Thank you. I didn't realise we could do that with CSS!

To get my images to fit on A4 I had to do:
```
img {
  max-width: 960px;
  width: 100%;
}
```
