### ISSUE TITLE
feature: Container markup for content following a heading

### ISSUE THREAD

**Issue by jonathanj** [simonhaenisch/md-to-pdf#63]
**Problem:**

I'm using `md-to-pdf` for generating a changelog PDF, the changelog has headings followed by content for each section. The problem I'm encountering is that the page break algorithm is a bit clueless about how to place good page breaks. Even if I add a style like `ul { page-break-inside: avoid; }` (which is guessing that the content is a single `ul`) I end up with headings left on their own at the bottom of pages.

**Solution:**

If the heading *and* the content after the heading was wrapped in a `div` with a known classname like `md-to-pdf--section-1` (for an H1), `md-to-pdf--section-2` (for an H2), etc. then I could add `page-break-inside: avoid` to _that_ element to get closer to what I want.

I know paged media in CSS has rough edges, I don't expect this to be a perfect solution that always page breaks exactly in the right place, but having tested this out (by modifying the HTML output by hand) it is a pretty good solution.

**Comment by simonhaenisch** [comment]
Hm it sounds like what you kind of want is to have a page-break before each heading? You could do that with the `::before` pseudo-element like this I guess (not tested):

```css
h1::before {
  content: '';
  display: block;
  page-break-after: always;
}
```

Otherwise you are also able to create your own divs because you can just put html inside markdown:

```md
<div class="section-one">

# Section One

</div>
```

**Comment by jonathanj** [comment]
Thanks for the suggestions @simonhaenisch.

I did consider the page break before headings case, but if the sections are short (sometimes that happens in a changelog) then I’m going to get lots of mostly empty pages in my PDF.

The HTML idea is a good suggestion that could work, it would require programmatic manipulation of the markdown document, since the document is already produced by this stage (by another piece of software). I’m avoiding it for now because of time constraints.

I’m going to close the issue, your suggestions are good enough that the additional functionality in md-to-pdf is not required. 

Thanks again.
