### ISSUE TITLE
PDF Options

### ISSUE THREAD

**Issue by gaitat** [simonhaenisch/md-to-pdf#65]
Trying to use `md2pdf document.md --pdf-options '{ "format": "Letter" }'` as is described in `md2pdf --help`
In version 2.8.2 I get `Unexpected token ' in JSON at position 0`
In version 3.0.0-pre.1 I get:
npx md2pdf .\user_guide\GenViz-UserGuide.md --pdf-options '{ "format": "Letter" }'
  × generating PDF from .\user_guide\GenViz-UserGuide.md
    → Unexpected token ' in JSON at position 0
  × generating PDF from format:
    → ENOENT: no such file or directory, open '...:'
  × generating PDF from Letter
    → ENOENT: no such file or directory, open '...'
  × generating PDF from }'
    → ENOENT: no such file or directory, open '...}''

**Comment by simonhaenisch** [comment]
Hm this works for me but I'm not currently able to test this on Windows.

Maybe it's not possible to use single quotes as string delimiters in your terminal?

Anyway, I noticed that `"margin": null` from the example doesn't actually work, so i need to remove that from the examples.

**Comment by miklosz** [comment]
Had the same issue on Win, escaping quotes solves the problem
`--pdf-options "{ \"margin\": \"10mm\" }"`

**Comment by aescolastico** [comment]
FYI this is still an issue on windows. For me, I had to escape the double quotes in the json like @miklosz said, but you have to use single quotes to terminate the string. Like this:
``
 --pdf-options '{ \"format\": \"Letter\", \"margin\": \"20mm\", \"printBackground\": true }'
``

**Comment by simonhaenisch** [comment]
Ok thanks for the info... there's nothing that can be done about this though. Double quotes inside single quotes works fine in bash-like shells on Unix systems. I'm unfamiliar with how strings and quotes work in Windows shells but escaped double quotes should usually work even within a double-quoted string 🤷🏻‍♂️
