### ISSUE TITLE
Why using a http server ?

### ISSUE THREAD

**Issue by jooola** [simonhaenisch/md-to-pdf#66]
Everything is in the title, I wonder why you had to use a http server in order to print the html files ?
Why not load the files directly inside puppeteer, using `files:///path/to/file.html` ?

**Comment by simonhaenisch** [comment]
It might potentially work, tbh I just haven't tried. I know there's some limitations with the file protocol and I just didn't want to deal with them. You can give it a try if you want and let me know how it goes 🤓

**Comment by jooola** [comment]
@simonhaenisch Could you please raise a few concerns about the file protocol ? I don't want to stumble on something that you might already have considered.

**Comment by simonhaenisch** [comment]
cross-origin requests
