### ISSUE TITLE
bug: Landscape mode not working

### ISSUE THREAD

**Issue by ThijsBorst** [simonhaenisch/md-to-pdf#67]
**Context:**

- version: 3.0.0
- platform: Windows
- node version: 12.10.0

**Describe the bug:**

Set the landscape option in the pdf_options for puppeteer as this is described in the puppeteer options: https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagepdfoptions

Expected behavior is an output with landscape oriented pages, but I get portrait oriented pages.

Code: 

`
    const options = {
        content: fileContents,
        pdf_options: {
            landscape: true,
            format: "A4"
        }
    }
    await mdToPdf(options, { dest: './file.pdf' });
`

**Comment by simonhaenisch** [comment]
I think you're just using the API incorrectly. The `pdf_options` field needs to be part of the second (config) argument:

```js
const options = {
  dest: './file.pdf',
  pdf_options: { landscape: true, format: "A4" }
}

await mdToPdf({ content: fileContents }, options)
```

Let me know if this doesn't work for you.
