### ISSUE TITLE
bug: Shift headings to a next page

### ISSUE THREAD

**Issue by zemse** [simonhaenisch/md-to-pdf#72]
**Context:**

- version (`md-to-pdf -v`): 3.1.0
- platform (Unix, macOS, Windows): macOS
- node version: 13.8.0

**Describe the bug:**

When there is less space available to fit the heading along with atleast one sentence on the page, the heading text is last in the page while it's content is on the next page. That looks a bit weird like it's printed by a machine who doesn't know what's the content and it just print it. 

https://www.dropbox.com/s/6ulwfs0dv7rusig/Screenshot%202020-04-25%2020.30.21.png?dl=0

While on Apple Pages in macOS, when there is not enough space, it automatically takes the heading to the next page if content for the heading can't be started in the same page.

If we can give that effect of shifting the heading to new page if even one line of content can't be adjusted then it would be extremely awesome.

**Comment by simonhaenisch** [comment]
It's not technically possible to automate this with Chromium's PDF printing afaik (I'd like to be proven wrong though 🤓). You have to consider the underlying toolchain... printing a document rendered as a web page is not like a full-blown text editor application. You might be better off with LaTeX if you want the layout to be taken care of automatically.

Personally, I just add manual page breaks (see readme for how to do that)... I remember I used to put a page break before every major section header.
