### ISSUE TITLE
bug: Wrong rendering of emphasis using asterisks

### ISSUE THREAD

**Issue by petergardfjall** [simonhaenisch/md-to-pdf#78]
**Context:**

- version (`md-to-pdf -v`): 3.1.1
- platform (Unix, macOS, Windows): Linux
- node version: v12.19.0

**Describe the bug:**

It seems like the used version of `marked` (`v1.1.1`) has a problem in rendering emphasis with asterisks (https://github.com/markedjs/marked/issues/1754).

For example, the following example

    $ echo "*A pigeon*: a  type of *bird*" | md-to-pdf --as-html

I would expect to result in HTML such as

```
<body class="">
<p><em>A pigeon</em>: a  type of <em>bird</em></p>
</body></html>
```

Actually results in:

```
<body class="">
<p><em>A pigeon*: a  type of *bird</em></p>
</body></html>
```

The fix appears to be fixed in marked v1.1.2 (https://github.com/markedjs/marked/issues/1754#issuecomment-713628483) so please consider upgrading.

**Comment by simonhaenisch** [comment]
Thanks for the issue, yeah i'll upgrade now!

**Comment by petergardfjall** [comment]
@simonhaenisch  I just submitted a PR: https://github.com/simonhaenisch/md-to-pdf/pull/79

**Comment by simonhaenisch** [comment]
3.1.2 is published on npm now 🤓  cheers 🎉

**Comment by petergardfjall** [comment]
Wow, that was fast! Thanks!
