### ISSUE TITLE
Add TOC (Table Of Contents) feature

### ISSUE THREAD

**Issue by simonhaenisch** [simonhaenisch/md-to-pdf#9]
~Add a `--toc` cli argument to~ Use a `.toc` class or `<!-- TOC -->` comment to enable a TOC generator and inject an auto-generated TOC into the html.

**Comment by abhi3700** [comment]
Even I faced it too....
Pls, make that a priority.

**Comment by simonhaenisch** [comment]
I implemented a simple TOC:

![image](https://user-images.githubusercontent.com/3410759/39786777-2bd9f51a-5376-11e8-89b8-2d764b430792.png)

However links are not working yet (this being a limitation of `phantomjs` which is the underlying generator for `html-pdf`, see ariya/phantomjs#13959), and I'm also not yet sure about how page numbers can be implemented (but it should be possible using the info about page format/size, borders and the top offset of the heading elements).

If you want to use it, you can just use the [feature-toc](/simonhaenisch/md-to-pdf/tree/feature-toc) branch for now, and add the following to your markdown document:

```html
## Table of Contents

<div class="toc"></div>
```

If you need working internal links, a switch over from `html-pdf`/`phantomjs` to [headless Chrome](/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions) would also fix it, but that would be a major refactor and would require the user to install Chrome.

**Comment by simonhaenisch** [comment]
@abhi3700 I'm not sure I understand what you mean... this issue is about automatically generating a TOC from all the headings in the markdown document.

What do you mean by the TOC being created in the markdown format? Are you saying that you are manually adding the entries to your `.md` file? If so, why would they not be in the PDF? Or is this regarding the styling of the TOC? Can you show an example of your code and your expected outcome, please?

**Comment by abhi3700** [comment]
@simonhaenisch 
Actually, I am saying about this-
For creating a table in .md format, we use this -
S.no | Name | DOB
-----|--------|------
1 | abhijit | march
2 | akash | april

But, this doesn't get converted using your cli arguments.

Please, look at the issue.

**Comment by simonhaenisch** [comment]
Ah ok, you are talking about actual tables, that is not related to this issue (see [Table of Contents](https://en.wikipedia.org/wiki/Table_of_contents).

Tables are supported, however there are no default table styles included yet. Your example renders like this for me:

![screen shot 2018-05-23 at 9 24 35 am](https://user-images.githubusercontent.com/3410759/40391023-24f6ed84-5e6b-11e8-836e-25e03e762a12.png)

As you can see, it is a table, but there is just no css styling yet. I'll add some later. In the meantime you can also try using the github markdown css as explained in the [readme](/simonhaenisch/md-to-pdf#github-styles):

```markdown
---
stylesheet: https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.10.0/github-markdown.min.css
body_class: markdown-body
css: >-
  .markdown-body { font-size: 11px; }
  .markdown-body pre>code { white-space: pre-wrap; }
---

S.no | Name | DOB
-----|--------|------
1 | abhijit | march
2 | akash | april
```

Will render like this:

![image](https://user-images.githubusercontent.com/3410759/40391258-c455c09e-5e6b-11e8-8a2a-c9e70f6b451c.png)

**Comment by simonhaenisch** [comment]
Closing this for now because I don't really like the original approach I took. This can be solved in user-land (e. g. with a custom renderer or by adding a script somewhere in the page). If a marked plugin for generating TOCs comes up, I'll have another look at integrating this.
