### ISSUE TITLE
feature: repeat background image in multi-page PDF on follow up pages

### ISSUE THREAD

**Issue by dennisppaul** [simonhaenisch/md-to-pdf#90]
**Problem:**

When generating a multi-page PDF with background image ( e.g letter head as SVG ), the image is not repeated on the follow up page ( p2 ff ). 

**Solution:**

Repeat the background image on follow up pages.

**Comment by simonhaenisch** [comment]
I'm not sure what you mean exactly, can you share a code example so I can reproduce your problem?
