### ISSUE TITLE
bug: it hangs in Docker

### ISSUE THREAD

**Issue by purerosefallen** [simonhaenisch/md-to-pdf#91]
**Context:**

- version (`md-to-pdf -v`): `"md-to-pdf": "^3.3.2",`
- platform (Unix, macOS, Windows): Ubuntu 20.04.2 LTS on my desktop, but it runs in Docker
- node version: v14.15.0

**Describe the bug:**

I'm trying to make a Nest.js application generating a PDF file from markdown, but.. when it runs it stucks.

some code inside my application:

```ts
  async getPdf(data: ScoreSheetData) {
    this.log.log(`Rendering PDF with data ${JSON.stringify(data)}`);
    const renderedMarkdownContent = mustache.render(this.template, data, null, {
      escape: (v) => v,
    });
    const { content } = await mdToPdf(
      { content: renderedMarkdownContent },
      {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        launch_options: { args: ['--no-sandbox', '--disable-setuid-sandbox'] },
      },
    );
    return content;
  }
```

Dockerfile: 

```dockerfile
FROM node:buster-slim
LABEL Author="Nanahira <nanahira@momobako.com>"

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y python3 build-essential google-chrome-stable fonts-ipafont-gothic fonts-wqy-microhei fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm ci
COPY . ./
RUN npm run build

CMD ["npm", "run", "start:prod"]

```

On my development desktop it runs perfectly, but in docker.. it just went stuck when it renders the pdf file.
asking for help... thanks in advance.

**Comment by simonhaenisch** [comment]
Hi, have you seen #83? Maybe there's some related info there that can help you solve it. Otherwise, you could try adding some console logs in the source (either clone this or modify the compiled code in `node_modules/md-to-pdf/dist`) to figure out where exactly it hangs. Maybe around some of these lines?

https://github.com/simonhaenisch/md-to-pdf/blob/c26370eea81401a63ab489bb5c412a14b7182e8e/src/index.ts#L55

https://github.com/simonhaenisch/md-to-pdf/blob/c26370eea81401a63ab489bb5c412a14b7182e8e/src/lib/generate-output.ts#L51-L54

**Comment by purerosefallen** [comment]
]

**Comment by mrflip** [comment]
Here is a gist demonstrating md-to-pdf on the official `node:18.9-alpine3.15` node docker image:

https://gist.github.com/mrflip/9b8d598e5f06f210bfed9f7c4972cafa

It is running as a regular user and supplying the `--no-sandbox` flag. If you'd like I can make a PR with this.
