### ISSUE TITLE
Can't start browser process in pipeline using node:latest

### ISSUE THREAD

**Issue by Regenhardt** [simonhaenisch/md-to-pdf#92]
**Context:**

- version 3.3.2
- platform Linux
- node version 16

**Describe the bug:**

Trying to build a readme.md file using the following job description:

```
Node-md-to-pdf:
  stage: print
  image: node:latest
  script:
    - npm i -g md-to-pdf@latest
    - md-to-pdf ./readme.md
  artifacts:
    paths:
      - "*.pdf"
```

it always fails to start the browser process, with the following error message:

```
d-to-pdf[08:40:44] generating PDF from ./readme.md [started]
[08:40:44] generating PDF from ./readme.md [failed]
[08:40:44] → Failed to launch the browser process!
/usr/local/lib/node_modules/md-to-pdf/node_modules/puppeteer/.local-chromium/linux-884014/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
ListrError: Something went wrong
    at /usr/local/lib/node_modules/md-to-pdf/node_modules/listr/index.js:102:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/usr/local/lib/node_modules/md-to-pdf/dist/cli.js:116:5) {
  errors: [
    Error: Failed to launch the browser process!
    /usr/local/lib/node_modules/md-to-pdf/node_modules/puppeteer/.local-chromium/linux-884014/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
    
    
    TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    
        at onClose (/usr/local/lib/node_modules/md-to-pdf/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:20)
        at Interface.<anonymous> (/usr/local/lib/node_modules/md-to-pdf/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:184:68)
        at Interface.emit (node:events:406:35)
        at Interface.close (node:readline:586:8)
        at Socket.onend (node:readline:277:10)
        at Socket.emit (node:events:406:35)
        at endReadableNT (node:internal/streams/readable:1329:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21)
  ],
  context: [Object: null prototype] {}
}
```

Not sure how I could fix anything about a puppeteer problem here, since all I do is install md-to-pdf, which in turn installs its own packages. Anything I could try or that I'm obviously doing wrong?

**Comment by Regenhardt** [comment]
It does work on Windows, just going `npm i -g md-to-pdf` and then converting.

**Comment by Regenhardt** [comment]
Tried it with node:alpine first, then node:latest.

**Comment by simonhaenisch** [comment]
I'm not sure what pipeline service you're describing here. If you're talking about docker, you might need to use a `node-browser` image. Have you actually checked out the troubleshooting link in the error message? There's also other related closed issues about docker here already if you want to have a look.

> Not sure how I could fix anything about a puppeteer problem here, since all I do is install md-to-pdf, which in turn installs its own packages.

I think it's pretty clear from the repo description and readme that this uses headless Chromium (which is a browser)? This implies that you need to run `md-to-pdf` on a platform that can actually launch a browser, so yeah it's up to you to make sure that your platform can actually run the dependency packages (: My package using dependencies doesn't mean that it's my responsibility that these packages can run on your platform ;)

**Comment by Regenhardt** [comment]
Oh sorry, didn't know that. I just saw the fail coming from node_modules/md-to-pdf/node_module and figured chromium gets installed alongside this package. Trying it with a preinstalled browser.

**Comment by simonhaenisch** [comment]
Yes, Chromium does get installed as a dependency! But the docker image still needs to support running a browser (which is easiest by using an image that comes with browsers). You can instead also install a long list of dependency packages so that it can run Chromium. See https://github.com/simonhaenisch/md-to-pdf/issues/91#issuecomment-850051154 or https://github.com/simonhaenisch/md-to-pdf/issues/83#issuecomment-792270650.

**Comment by Regenhardt** [comment]
Unfortunately not yet, still playing around with different images, do have a promising idea to use one usually used for cypress. After sleeping though.

**Comment by Regenhardt** [comment]
Damn, now getting `[0607/123749.888897:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.` - where the link goes to a bug thread. That is something I'll have to read later, I didn't expect to go deep into chromium stuff.

**Comment by simonhaenisch** [comment]
Yeah in a lot of linux CI environments you have to configure sandboxing. It's in the troubleshooting link in your original error message, specifically this section: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox

You can try with `md-to-pdf --launch-options '{ "args": ["--no-sandbox", "--disable-setuid-sandbox"] }'`, or configure/find an image that supports sandboxing.

BTW I still don't know which CI platform you're actually using. I've used CircleCI with this package and it worked without any issues with the `node-browsers` image. A long while ago I switched to Github Actions and same thing, no issues. You can see the workflow here:

https://github.com/simonhaenisch/md-to-pdf/blob/c26370eea81401a63ab489bb5c412a14b7182e8e/.github/workflows/main.yml#L23-L48

**Comment by Regenhardt** [comment]
Haha whoops, I'm using Gitlab, the university provides the whole package to us. 

Using circleci/node:latest-browsers, I got yet another totally different error message, it seems that image won't let me install md-to-pdf: `npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/md-to-pdf'`

The no-sandboxing options are working though, thanks for the help :D
