### ISSUE TITLE
pdf change in git, even when there is no change

### ISSUE THREAD

**Issue by TomL-dev** [simonhaenisch/md-to-pdf#93]
**Context:**

- version (`md-to-pdf -v`): 3.3.2
- platform (Unix, macOS, Windows): macOS & redhat
- node version: v14.17.0

**Describe the bug:**

Every time i run `cat foo.md | node_modules/md-to-pdf/dist/cli.js > out.pdf` i get a pdf just as i like.
however every time git states there are changes to the file, even if there are no changes (visible to me at least) to the md or the pdf file. 
what is causing this change to be recognized by git?

this is an issue for me, because in my azure pipeline i generate the pdfs from all the markdowns i have. and in the pipeline i push them back to the branch. This is however causing a new trigger of the pipeline, because git thinks there are changes to the pdf files.

**Comment by simonhaenisch** [comment]
I assume there's some sort of creation timestamp embedded in the pdf that changes every time you regenerate it? I'm not a pro when it comes to PDFs... you can try viewing the diff in a text editor, the PDF file content is actually somewhat readable when you open it as plain text.

Anyway, this doesn't have much to do with this tool, or at least there's nothing I can change to cater for this specific use case. In general you probably don't want to add generated files to source control but rather some other kind of storage (there are many options, e. g. Azure File Storage, AWS S3, Google Cloud Storage, Vercel, Netlify).

**Comment by simonhaenisch** [comment]
Just an idea: you can tell your Azure pipeline to only trigger if files changed in certain paths, using a path filter. I've done this before. See https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#paths. You'd need to generate your files into a certain path, and then exclude that one for the trigger.
